[package]
name = "swiss-pairings"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
itertools = "0.10"
permutator = "0.4"
anyhow = "1.0.80"

[dev-dependencies]
dotenv = "0.15.0"
