[package]
name = "swiss-pairings"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
anyhow = "1.0.80"
thiserror = "1.0.58"

[dev-dependencies]
dotenv = "0.15.0"
